export const initialState = {
  config: {
    topic: 'Hospital Admissions Data',
    protectedAttribute: 'Hospitalization Outcome',
    protectedAttributeColumn: 'OUTCOME',
    constraints: {},
    windowSize: 10,
    blockSize: 5,
    landmarkSize: 5,
    kafkaTopic: 'hospital-stream',
  },
  phase: 'config',
  currentWindowIndex: 0,
  windows: [],
  moviePool: [],
  poolCursor: 0,
  landmarkCounter: 0,
  landmarkActive: false,
  windowHistory: [],
  activeBlockIndex: 0,
  demoScenario: 0,
  pendingLandmarkAffected: 0,
};
